export const weatherCodes:{[key:number]:string} = {
  0: "Açıq səma",
  1: "Əsasən açıq",
  2: "Qismən buludlu",
  3: "Tutğun",
  45: "Dumanlı",
  48: "Dumanlı",
  51: "Yağış: Yüngül intensiv",
  53: "Yağış: Orta intensiv",
  55: "Yağış: Sıx intensiv",
  56: "Sulu qar: Yüngül intensiv",
  57: "Sulu qar: Sıx intensiv",
  61: "Yağış: Az intensiv",
  63: "Yağış: Orta intensiv",
  65: "Yağış: Güclü intensiv",
  66: "Sulu qar: Az intensiv",
  67: "Sulu qar: Güclü intensiv",
  71: "Qar: Yüngül intensiv",
  73: "Qar: Orta intensiv",
  75: "Qar: Güclü intensiv",
  77: "Qar dənəcikləri",
  80: "Yağış: Yüngül intensiv",
  81: "Yağış: Orta intensiv",
  82: "Yağış: Güclü intensiv",
  85: "Qar yağışı: Yüngül intensiv",
  86: "Qar yağışı: Güclü intensiv",
  95: "Fırtına: Yüngül və orta intensiv",
  96: "Fırtına: Yüngül dolu",
  99: "Fırtına: Güclü dolu",
};

