// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  post_body: dynamic(() => import("./PostBody")),
  title: dynamic(() => import("./Title")),
};
